---
driver:
  name: ec2 

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  #require_chef_omnibus: "13.8.5"

verifier:
  name: inspec

platforms:
  - name: rhel-7 
    driver:
      image_id: ami-011b3ccf1bd6db744 

suites:
  - name: default
    run_list:
      - recipe[dou_vault_installer::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
